### ISSUE TITLE
Cannot compile with error '_Fmt_string' is not a member of 'std'

### ISSUE THREAD

**Issue by poirierlouis** [psiberx/cp2077-red-lib#1]
I'm currently writing my own template to get used to RED4ext, redscript. I found your library truly convenient, thanks.

However, compiling my project with yours gives me errors at:
https://github.com/psiberx/cp2077-red-lib/blob/830d94f4c63eb637daf4c48d71dbdee566ae402f/include/Red/LogChannel.hpp#L28
https://github.com/psiberx/cp2077-red-lib/blob/830d94f4c63eb637daf4c48d71dbdee566ae402f/include/Red/LogChannel.hpp#L34

Replacing `std::_Fmt_string` with `std::format_string` solved it.

NB: I could not found official documentation related to '_Fmt_string' in 'std'. Is it linked to a specific setup of your environment?

**Comment by psiberx** [comment]
It's an MSVC non-standard implementation of format string as a constant expression. I use it since C++20 doesn't expose `std::format_string` (see [P2508](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2508r2.html)). So yeah it's MSVC dependent. I'll switch to standard with C++23.

**Comment by psiberx** [comment]
I've updated couple of things to be compatible with the latest MSVC.
