### ISSUE TITLE
Cannot compile with error 'SystemBuilder' : identifier not found

### ISSUE THREAD

**Issue by poirierlouis** [psiberx/cp2077-red-lib#2]
I'm having an error which fails compilation with message:
> Error C3861: '[SystemBuilder](https://github.com/psiberx/cp2077-red-lib/blob/830d94f4c63eb637daf4c48d71dbdee566ae402f/include/Red/TypeInfo/Definition.hpp#L985)' : identifier not found

It fails when compiling [Red::ClassDefinition<TClass>](https://github.com/psiberx/cp2077-red-lib/blob/830d94f4c63eb637daf4c48d71dbdee566ae402f/include/Red/TypeInfo/Definition.hpp#L907). Reordering these declarations with `SystemBuilder` first and then `ClassDefinition` solved this error for me. I'm not sure though if I'm simply missing some flags in my environment...

**Comment by psiberx** [comment]
You can open PR to move definition.
